p = input("Kérem a robot parancsait:")
def f(c): return len(list(filter(lambda x: x == c, p)))
def mo(a, b): return a * (f(a) - f(b)) if f(a) > f(b) else  b * (f(b) - f(a))
for b in "EDKN": print(b, "betűk száma:", f(b))
print("Egy legrövidebb út parancsszava:", mo("E", "D") + mo("K", "N"))